# Generated by Django 4.2.6 on 2023-10-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("streak", models.IntegerField(default=0)),
                ("daily_percentage", models.FloatField(default=0)),
                ("daily_total", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vocab", models.CharField(max_length=255)),
                (
                    "collection",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wordwise.collection"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("definition", models.CharField(max_length=255)),
                ("part_of_speech", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wordwise.word")),
            ],
        ),
    ]
