# Generated by Django 4.2.6 on 2023-11-02 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("example", models.CharField(max_length=255)),
                (
                    "example_of",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wordwise.definition"),
                ),
            ],
        ),
    ]
