# Generated by Django 4.2.6 on 2023-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="id",
        ),
        migrations.RemoveField(
            model_name="word",
            name="collection",
        ),
        migrations.AlterField(
            model_name="word",
            name="vocab",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="word",
            name="collection",
            field=models.ManyToManyField(to="wordwise.collection"),
        ),
    ]
