# Generated by Django 4.2.6 on 2023-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0002_example"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="collection",
        ),
        migrations.AddField(
            model_name="definition",
            name="collection",
            field=models.ManyToManyField(to="wordwise.collection"),
        ),
        migrations.AddField(
            model_name="userdata",
            name="favorite",
            field=models.ManyToManyField(to="wordwise.definition"),
        ),
        migrations.AlterField(
            model_name="definition",
            name="part_of_speech",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
