# Generated by Django 4.2.6 on 2023-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0002_remove_word_id_remove_word_collection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOf",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type_of", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="definition",
            name="category",
        ),
        migrations.AddField(
            model_name="definition",
            name="type_of",
            field=models.ManyToManyField(to="wordwise.typeof"),
        ),
    ]
