# Generated by Django 4.2.6 on 2023-11-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0003_remove_word_collection_definition_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
