# Generated by Django 4.2.6 on 2023-11-12 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wordwise", "0004_collection_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="WordDeck",
        ),
    ]
