# Generated by Django 4.2.6 on 2023-11-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0005_rename_collection_worddeck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeof",
            name="type_of",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="vocab",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
