# Generated by Django 4.2.6 on 2023-11-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0006_alter_typeof_type_of_alter_word_vocab"),
    ]

    operations = [
        migrations.AddField(
            model_name="worddeck",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
