# Generated by Django 4.2.6 on 2023-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wordwise", "0008_memorisestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="definition",
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name="example",
            name="example",
            field=models.CharField(max_length=755),
        ),
    ]
